config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/edit/:id', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
    # raise
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params_task)
    # raise
    if @task.save
      redirect_to tasks_path
    else
      render :new, status: :unprocessable_entry
    end
  end

  def edit
  end

  def update
    @task.update(params_task)
    redirect_to tasks_path(@tasks)
  end

  def show
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def params_task
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="card">
    <h1 class="text-center">Edit Task</h1>
    <%= form_with model: @task, class: "doggos_form" do |f| %>
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title %>
      <%= f.label :details %>
      <%= f.text_field :details %>
      <%= f.label :completed %>
      <%= f.check_box  :completed %>
      <%= f.submit %>
    <% end %>
    <%= link_to "Back to list", tasks_path, class: "text-decoration-none" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="card">
    <h1 class="text-center">Task List</h1>
      <ul class="list-group list-group-flush">
        <% @tasks.each do |task| %>
        <li class="list-group-item">
          <input type="checkbox" name="" id="" <%= "checked" if task.completed %>>
          <%= link_to task.title, task_path(task) %>
          <i class="bi bi-archive"></i>
          <%= link_to "Delete", task_path(task),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
           %>
        </li>
        <% end %>
      </ul>
      <%= link_to "Add a new task", new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="card">
    <h1 class="text-center">New Task</h1>
    <%= form_with model: @task, class: "doggos_form" do |f| %>
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title %>
      <%= f.label :details %>
      <%= f.text_field :details %>
      <%= f.submit %>
    <% end %>
    <%= link_to "Back to list", tasks_path, class: "text-decoration-none" %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="card">
    <h1 class="text-center"><%= @task.title %></h1>
    <%= link_to "Edit this task", edit_task_path(@task) %><br>
    <div class="card">
      <div class="card-body">
        <p><%= @task.details  %></p>
      </div>
    </div>
    <div class="form-check">
      <input type="checkbox" name="" id="task_status" <%= "checked" if @task.completed %>>
      <label for="task_status">this task is completed</label>
    </div>
    <%= link_to "Back to list", tasks_path %>
  </div>
</div>